#########################
# Static tool & environment definition paths
#########################
snakemake_sif:
  /home/groups/nmrl/image_files/snakemake.sif
mlst_quast_sif:
  /home/groups/nmrl/image_files/mlst_quast.sif
krona_sif:
  /home/groups/nmrl/image_files/krona.sif
rgi_env:
  /home/groups/nmrl/bact_analysis/NMRL_Bact_Assembly_Inhouse/conda_defs/rgi_env.yaml
nextflow_env:
  /home/groups/nmrl/bact_analysis/NMRL_Bact_Assembly_Inhouse/conda_defs/nextflow.yaml
kraken2_env:
  /home/groups/nmrl/bact_analysis/NMRL_Bact_Assembly_Inhouse/conda_defs/kraken2.yaml
lissero_sif:
  /home/groups/nmrl/image_files/lissero_latest.sif
seqsero_sif:
  /home/groups/nmrl/image_files/seqsero2_latest.sif
sistr_sif:
  /home/groups/nmrl/image_files/sistr_latest.sif
hamronization_sif:
  /home/groups/nmrl/image_files/hamronization_latest.sif
resfinder_sif:
  /mnt/home/groups/nmrl/image_files/resfinder.sif
mob_suite_sif:
  /mnt/home/groups/nmrl/image_files/mob_suite_3.0.3.sif
amrpp_repo:
  /mnt/home/groups/nmrl/bact_analysis/amrplusplus_v2/
home_dir:
  /mnt/home/groups/nmrl/bact_analysis/NMRL_Bact_Assembly_Inhouse/
work_dir:
  ./data/


#########################
# bact_core configuration
#########################
core_target_files:
output_directory:

core_tool_configs:
  kraken2:
    threads: 12
    human_db: /mnt/home/groups/nmrl/db/db-kraken2/human_reference/
    bact_db: /mnt/home/groups/nmrl/db/db-kraken2/full_ref_bafp/
  shovill:
    minlen: 1
    ram: 36
    depth: 100


#########################
# bact_shell configuration
#########################
shell_target_files:

shell_tool_configs:
#Configuration settings for each tool used by bact_shell snakefile
  amr_plusplus:
    threads: 24
  resfinder:
    length: 0.6
    coverage: 0.9
    resfinder_db: /mnt/home/groups/nmrl/db/db-resfinder/


#########################
# bact_tip configuration
#########################
tip_target_files:
 
tip_tool_configs:
#Configuration settings for each tool used by bact_tip snakefile
  hicup:
  meningotype:
  legsta:
  MTBSeq:
  Kleborate:
  Kaptive:
    #?
  spaTyper:
  AgrVATE:
    #?
  spaTYper:
  staphopia-sccmec:
  emmtyper:
  ngmaster:
    #?
  lissero:
  seqsero:
  sistr:
 
  

#########################
# bact_shape configuration
#########################
shape_target_files:
  #List of target files supplied by the wrapper & wildcard definition strings

shape_tool_configs:
#Configuration settings for each tool used by bact_shape snakefile
  hamronization: