home_dir:
    ~/bact_output/
target_dir:
    /home/groups/nmrl/bact_analysis/bact_input/test/
kfinder_threads: 5
kfinder_db: bacteria
shovill_params:
    depth: 95 #100
    # k1: 31 #31
    # k2: 33 #33
    # k3: 55 #55
    # k4: 77 #77
    # k5: 99 #99
    # k6: 127 #127
    ram: 7
    minlen: 500
