name: Trigger aquamis QC threshold update based on push to ardetype/config_files/update_aquamis_thresholds

on:
 push:
   branches:  [ ardetype ]
   paths:
     - "config_files/update_aquamis_thresholds"
     - .github/workflows/update_ardetype_thresholds.yml
jobs:
  wget:
    runs-on: ubuntu-latest
    steps:
    - name: wget
      uses: wei/wget@v1
      with:
        args: -O AQUAMIS_thresholds.json wget https://gitlab.com/bfr_bioinformatics/AQUAMIS/-/raw/master/resources/AQUAMIS_thresholds.json?ref_type=heads
    - name: Update thresholds on HPC
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.HPC_HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASS }}
        local: /home/runner/work/Ardetype/Ardetype/AQUAMIS_thresholds.json
        remote: ${{ secrets.HPC_DB }}AQUAMIS_thresholds.json
